global:
  scrape_interval: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'swarm-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['cdn_stack_swarm-exporter:9613']