global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'edge'
    metrics_path: /metrics
    static_configs:
      - targets: ['edge1:80','edge2:80']

  - job_name: 'origin'
    metrics_path: /metrics
    static_configs:
      - targets: ['origin:80']